# Generated by Django 5.2.7 on 2025-10-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('dosis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_toma', models.TimeField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Toma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_programada', models.DateTimeField()),
                ('fecha_hora_real', models.DateTimeField(blank=True, null=True)),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.horario')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.contacto')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.registro_toma')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_esp32', models.CharField(max_length=100)),
                ('estado_conexion', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.usuario'),
        ),
    ]
