# Generated by Django 6.0.3 on 2026-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
