# Generated by Django 5.2.17 on 2026-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
