# Generated by Django 5.2.17 on 2026-09-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_medicamento_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_modulo', models.PositiveIntegerField(help_text='Número físico o posición del módulo dentro del pastillero')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.dispositivo')),
                ('id_medicamento', models.OneToOneField(blank=True, help_text='Medicamento asignado al módulo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo', to='core.medicamento')),
            ],
            options={
                'ordering': ['id_dispositivo', 'numero_modulo'],
                'constraints': [models.UniqueConstraint(fields=('id_dispositivo', 'numero_modulo'), name='unique_modulo_por_dispositivo')],
            },
        ),
    ]
