# Generated by Django 5.2.17 on 2026-09-09 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dispositivo_iot_mvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_log', to='core.registro_toma')),
            ],
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048)),
                ('auth', models.CharField(max_length=255)),
                ('p256dh', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('browser', models.CharField(blank=True, default='', max_length=50)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to='core.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'endpoint'), name='unique_webpush_subscription_usuario_endpoint')],
            },
        ),
    ]
