# Generated by Django 5.2.17 on 2026-09-17 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_registro_toma_unico_por_horario_instante'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculacionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('puede_ver_medicamentos', models.BooleanField(default=True)),
                ('puede_ver_horarios', models.BooleanField(default=True)),
                ('puede_ver_registros', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulares', to='core.usuario')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to='core.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('titular', 'monitor'), name='unique_vinculacion_titular_monitor')],
            },
        ),
    ]
