# Generated by Django 5.2.17 on 2026-09-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vinculacionmonitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id_contacto',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='id_registro',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
