# Generated by Django 5.2.17 on 2026-10-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_enrolamiento_dispositivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventodispositivo',
            options={'ordering': ['-fecha_dispositivo', '-id']},
        ),
        migrations.AddField(
            model_name='eventodispositivo',
            name='datos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventodispositivo',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.modulo'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='detectado',
            field=models.BooleanField(default=False, help_text='La placa lo ve conectado en el bus I2C.'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='tapa_abierta',
            field=models.BooleanField(blank=True, help_text='Último estado de la tapa (sensor reed).', null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='ultimo_visto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_toma',
            name='apertura_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_toma',
            name='boton_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_toma',
            name='cierre_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_toma',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='core.modulo'),
        ),
        migrations.AddField(
            model_name='registro_toma',
            name='origen',
            field=models.CharField(choices=[('APP', 'Aplicación'), ('DISPOSITIVO', 'Pastillero')], default='APP', max_length=12),
        ),
    ]
